# Generated by Django 5.1 on 2024-08-18 13:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=100)),
                ('question_content', models.CharField(max_length=200, unique=True)),
                ('question_choices', models.TextField(max_length=500)),
                ('answer', models.CharField(max_length=100)),
                ('mark', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('unit', models.CharField(max_length=20)),
                ('mix_choices', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='exam_questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
